services:
  event-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  event-service:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://event-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "19090:19090"
    depends_on:
      - event-db

volumes:
  db_data: