server:
  port: ${AUTH_PORT}  # Auth 서비스의 포트 설정

jwt:
  secret: ${JWT_SECRET_KEY}  # JWT 토큰 생성에 사용할 시크릿 키
  expiration: ${JWT_EXPIRATION_TIME}  # JWT 만료 시간

feign:
  client:
    config:
      default:
        connect-timeout: 5000  # 타임아웃 설정 (연결)
        read-timeout: 5000     # 타임아웃 설정 (응답)

# Feign Client를 통해 호출하는 user-service 설정
user-service:
  name: ${USER_SERVICE_NAME}  # internal 호출용 FeignClient에서 참조할 서비스 이름
  url: ${USER_SERVICE_URL}  # internal 호출용 URL

logging:
  level:
    com.ticketing.auth-service: DEBUG  # Auth 서비스 패키지에 대한 디버그 로깅