spring:
  application:
    name: payment-service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_batch_fetch_size: 100

---
spring.config.activate.on-profile: local

server:
  port: ${PAYMENT_PORT}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: ${RDS_HOST}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: org.postgresql.Driver

kakao:
  pay:
    secret-key: ${KAKAO_PAY_SECRET_KEY}
    url: ${KAKAO_PAY_URL}


