server:
  port: ${PAYMENT_PORT}

spring:
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: ${RDS_HOST}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: org.postgresql.Driver

kakao:
  pay:
    secret-key: ${KAKAO_PAY_SECRET_KEY}
    url: ${KAKAO_PAY_URL}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/