server:
  port: ${USER_PORT}

spring:
  application:
    name: user-service
  datasource:
    url: ${USER_DB_DATABASE}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
    driver-class-name: ${USER_DB_DRIVER_CLASS}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: ${USER_DB_DDL}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
        format_sql: true
        highlight_sql: true

# swagger 사용시 패키지 이름까지 사용해서 구별하도록 설정
springdoc:
  use-fqn: true

# 로그 수준
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace