name: Staging

on:
  push:
    branches: [ecrtest]
jobs:
  staging:
    name: deploy to stating
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      #AWS - ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # JDK 17을 사용하도록 설정
          distribution: 'temurin'  # AdoptOpenJDK의 Temurin 배포판 사용

      # Grant execute permission to gradlew
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Clean Build
        run:
          ./gradlew clean build

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Cache Docker layers
#        uses: actions/cache@v4
#        with:
#          path: /tmp/.buildx-cache
#          key: ${{ runner.os }}-buildx-${{ github.sha }}
#          restore-keys: ${{ runner.os }}-buildx-

        # gateway
      - name: Gateway image to Amazon ECR
        id: build-gateway-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ipho-repository
          IMAGE_NAME: gateway
          IMAGE_TAG: latest
        run: |
          cd gateway-service
          docker build \
            --build-arg GATEWAY_PORT=${{ secrets.GATEWAY_PORT }} \
            --build-arg AUTH_SERVICE_URI=${{ secrets.AUTH_SERVICE_URI }} \
            --build-arg EVENT_SERVICE_URI=${{ secrets.EVENT_SERVICE_URI }} \
            --build-arg SEAT_SERVICE_URI=${{ secrets.SEAT_SERVICE_URI }} \
            --build-arg TICKET_SERVICE_URI=${{ secrets.TICKET_SERVICE_URI }} \
            --build-arg PAYMENT_SERVICE_URI=${{ secrets.PAYMENT_SERVICE_URI }} \
            --build-arg AUTH_SERVICE_INTERNAL_URL=${{ secrets.AUTH_SERVICE_INTERNAL_URL }} \
            --build-arg AUTH_SERVICE_NAME=${{ secrets.AUTH_SERVICE_NAME }} \
            --build-arg INTERNAL_SERVICE_URI=${{ secrets.INTERNAL_SERVICE_URI }} \
            --build-arg CACHE_EXPIRATION=${{ secrets.CACHE_EXPIRATION }} \
            --build-arg CACHE_MAX_SIZE=${{ secrets.CACHE_MAX_SIZE }} \
            -t $ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG" >> $GITHUB_ENV

      # auth-service
      - name: Auth image to Amazon ECR
        id: build-auth-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ipho-repository
          IMAGE_NAME: auth
          IMAGE_TAG: latest
        run: |
          cd auth-service
          docker build \
            --build-arg AUTH_PORT=${{ secrets.AUTH_PORT }} \
            --build-arg JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
            --build-arg JWT_EXPIRATION_TIME=${{ secrets.JWT_EXPIRATION_TIME }} \
            --build-arg USER_SERVICE_NAME=${{ secrets.USER_SERVICE_NAME }} \
            --build-arg USER_SERVICE_URL=${{ secrets.USER_SERVICE_URL }} \
            -t $ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG" >> $GITHUB_ENV

      # event-service
      - name: Event image to Amazon ECR
        id: build-event-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ipho-repository
          IMAGE_NAME: event
          IMAGE_TAG: latest
        run: |
          cd event-service
          docker build \
            --build-arg EVENT_PORT=${{ secrets.EVENT_PORT }} \
            --build-arg RDS_HOST=${{ secrets.RDS_HOST }} \
            --build-arg RDS_USERNAME=${{ secrets.RDS_USERNAME }} \
            --build-arg RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
            -t $ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG" >> $GITHUB_ENV

      # payment-service
      - name: Payment image to Amazon ECR
        id: build-payment-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ipho-repository
          IMAGE_NAME: payment
          IMAGE_TAG: latest
        run: |
          cd payment-service
           docker build \
            --build-arg SPRING_PROFILES_ACTIVE=local \
            --build-arg PAYMENT_PORT=${{ secrets.PAYMENT_PORT }} \
            --build-arg KAKAO_PAY_SECRET_KEY=${{ secrets.KAKAO_PAY_SECRET_KEY }} \
            --build-arg KAKAO_PAY_URL=${{ secrets.KAKAO_PAY_URL }} \
            --build-arg RDS_HOST=${{ secrets.RDS_HOST }} \
            --build-arg RDS_USERNAME=${{ secrets.RDS_USERNAME }} \
            --build-arg RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
            -t $ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG" >> $GITHUB_ENV

      # seat-service
      - name: Seat image to Amazon ECR
        id: build-seat-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ipho-repository
          IMAGE_NAME: seat
          IMAGE_TAG: latest
        run: |
          cd seat-service
          docker build \
            --build-arg SEAT_PORT=${{ secrets.SEAT_PORT }} \
            --build-arg RDS_HOST=${{ secrets.RDS_HOST }} \
            --build-arg RDS_USERNAME=${{ secrets.RDS_USERNAME }} \
            --build-arg RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
            -t $ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG" >> $GITHUB_ENV

      # ticket-service
      - name: Ticket image to Amazon ECR
        id: build-ticket-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ipho-repository
          IMAGE_NAME: ticket
          IMAGE_TAG: latest
        run: |
          cd ticket-service
          docker build \
            --build-arg TICKET_PORT=${{ secrets.TICKET_PORT }} \
            --build-arg RDS_HOST=${{ secrets.RDS_HOST }} \
            --build-arg RDS_USERNAME=${{ secrets.RDS_USERNAME }} \
            --build-arg RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
            -t $ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG" >> $GITHUB_ENV

      # user-service
      - name: User image to Amazon ECR
        id: build-user-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ipho-repository
          IMAGE_NAME: user
          IMAGE_TAG: latest
        run: |
          cd user-service
          docker build \
            --build-arg USER_PORT=${{ secrets.USER_PORT }} \
            --build-arg RDS_HOST=${{ secrets.RDS_HOST }} \
            --build-arg RDS_USERNAME=${{ secrets.RDS_USERNAME }} \
            --build-arg RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
            -t $ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG" >> $GITHUB_ENV
          
          

      - name: Download task definition for Gateway
        run: |
          aws ecs describe-task-definition --task-definition ipho-task-gateway \
          --query taskDefinition > /tmp/ipho-task-gateway.json

      - name: Download task definition for User
        run: |
          aws ecs describe-task-definition --task-definition ipho-task-user \
          --query taskDefinition > /tmp/ipho-task-user.json

      - name: Download task definition for Auth
        run: |
          aws ecs describe-task-definition --task-definition ipho-task-auth \
          --query taskDefinition > /tmp/ipho-task-auth.json

      - name: Download task definition for Event
        run: |
          aws ecs describe-task-definition --task-definition ipho-task-event \
          --query taskDefinition > /tmp/ipho-task-event.json

      - name: Download task definition for Seat
        run: |
          aws ecs describe-task-definition --task-definition ipho-task-seat \
          --query taskDefinition > /tmp/ipho-task-seat.json

      - name: Download task definition for Ticket
        run: |
          aws ecs describe-task-definition --task-definition ipho-task-ticket \
          --query taskDefinition > /tmp/ipho-task-ticket.json

      - name: Download task definition for Payment
        run: |
          aws ecs describe-task-definition --task-definition ipho-task-payment \
          --query taskDefinition > /tmp/ipho-task-payment.json
          
          
          

      - name: gateway-task-def update
        id: gateway-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: /tmp/ipho-task-gateway.json
          container-name: gateway-container
          image: ${{ steps.login_ecr.outputs.registry }}/ipho-repository/gateway:latest
          docker-labels: |
            SERVICE=gateway-service
            VERSION=latest

      - name: user-task-def update
        id: user-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: /tmp/ipho-task-user.json
          container-name: user-container
          image: ${{ steps.login_ecr.outputs.registry }}/ipho-repository/user:latest
          docker-labels: |
            SERVICE=user-service
            VERSION=latest

      - name: auth-task-def update
        id: auth-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: /tmp/ipho-task-auth.json
          container-name: auth-container
          image: ${{ steps.login_ecr.outputs.registry }}/ipho-repository/auth:latest
          docker-labels: |
            SERVICE=auth-service
            VERSION=latest

      - name: event-task-def update
        id: event-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: /tmp/ipho-task-event.json
          container-name: event-container
          image: ${{ steps.login_ecr.outputs.registry }}/ipho-repository/event:latest
          docker-labels: |
            SERVICE=event-service
            VERSION=latest

      - name: seat-task-def update
        id: seat-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: /tmp/ipho-task-seat.json
          container-name: seat-container
          image: ${{ steps.login_ecr.outputs.registry }}/ipho-repository/seat:latest
          docker-labels: |
            SERVICE=seat-service
            VERSION=latest

      - name: ticket-task-def update
        id: ticket-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: /tmp/ipho-task-ticket.json
          container-name: ticket-container
          image: ${{ steps.login_ecr.outputs.registry }}/ipho-repository/ticket:latest
          docker-labels: |
            SERVICE=ticket-service
            VERSION=latest

      - name: payment-task-def update
        id: payment-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: /tmp/ipho-task-payment.json
          container-name: payment-container
          image: ${{ steps.login_ecr.outputs.registry }}/ipho-repository/payment:latest
          docker-labels: |
            SERVICE=payment-service
            VERSION=latest

      - name: Deploy gateway
        id: deploy-gateway
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          cluster: ipho-cluster
          task-definition: ${{ steps.gateway-task-def.outputs.task-definition }}
          service: gateway-service
          wait-for-service-stability: true
          wait-for-minutes: 10

      - name: Deploy user
        id: deploy-user
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.user-task-def.outputs.task-definition }}
          cluster: ipho-cluster
          service: user-service
          wait-for-service-stability: true
          wait-for-minutes: 10

      - name: Deploy auth
        id: deploy-auth
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ipho-task-auth
          cluster: ipho-cluster
          service: auth-service
          wait-for-service-stability: true
          wait-for-minutes: 10

      - name: Deploy event
        id: deploy-event
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ipho-task-event
          cluster: ipho-cluster
          service: event-service
          wait-for-service-stability: true
          wait-for-minutes: 10

      - name: Deploy seat
        id: deploy-seat
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ipho-task-seat
          cluster: ipho-cluster
          service: seat-service
          wait-for-service-stability: true
          wait-for-minutes: 10

      - name: Deploy ticket
        id: deploy-ticket
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ipho-task-ticket
          cluster: ipho-cluster
          service: ticket-service
          wait-for-service-stability: true
          wait-for-minutes: 10

      - name: Deploy payment
        id: deploy-payment
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ipho-task-payment
          cluster: ipho-cluster
          service: payment-service
          wait-for-service-stability: true
          wait-for-minutes: 10